# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Limesctl < Formula
  desc "Command-line interface for Limes"
  homepage "https://github.com/sapcc/limesctl"
  version "3.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sapcc/limesctl/releases/download/v3.1.3/limesctl-3.1.3-darwin-arm64.tar.gz"
      sha256 "e651696446695cdaaab3ab1326f49617cd636bbd4a44e3b94f8dcc7782508078"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sapcc/limesctl/releases/download/v3.1.3/limesctl-3.1.3-darwin-amd64.tar.gz"
      sha256 "e0a92a908262654040aff8756c0950196cb450e898226c911ddfc29355497ef0"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sapcc/limesctl/releases/download/v3.1.3/limesctl-3.1.3-linux-arm64.tar.gz"
      sha256 "e052fe209821fdbcafd64ea1ea8ce88624cf1995413fd015ff033cbecb50e3ec"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sapcc/limesctl/releases/download/v3.1.3/limesctl-3.1.3-linux-amd64.tar.gz"
      sha256 "193dd64568bd17d8ecf8c7d048e449542f11285f52670af480d83e4e7d099a47"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
  end

  test do
    system "#{bin}/limesctl --version"
  end
end
