# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Limesctl < Formula
  desc "Command-line interface for Limes"
  homepage "https://github.com/sapcc/limesctl"
  version "3.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sapcc/limesctl/releases/download/v3.1.2/limesctl-3.1.2-darwin-arm64.tar.gz"
      sha256 "bbfa15a805de7d10e8445db2d78d13859fac7878e58cb547c2441472ca315b1e"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sapcc/limesctl/releases/download/v3.1.2/limesctl-3.1.2-darwin-amd64.tar.gz"
      sha256 "9350fbf514aebf956ddb392344a3d96d317b895dfc563a116dd55b2ac091cda6"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sapcc/limesctl/releases/download/v3.1.2/limesctl-3.1.2-linux-arm64.tar.gz"
      sha256 "954102b1624fc7ecddfac1af5c45b9d13f79e5bc51eb194fd459451d044b1a5d"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sapcc/limesctl/releases/download/v3.1.2/limesctl-3.1.2-linux-amd64.tar.gz"
      sha256 "ebc8d6e33115509348ccdda51bac2fa3993214607e263d12b60dd2b4594ab992"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
  end

  test do
    system "#{bin}/limesctl --version"
  end
end
