# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Limesctl < Formula
  desc "Command-line interface for Limes"
  homepage "https://github.com/sapcc/limesctl"
  version "3.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sapcc/limesctl/releases/download/v3.2.0/limesctl-3.2.0-darwin-arm64.tar.gz"
      sha256 "f841fc3469745ceae63472c7258f97c67c78bf6b14737911e72b19b82a94b3d0"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sapcc/limesctl/releases/download/v3.2.0/limesctl-3.2.0-darwin-amd64.tar.gz"
      sha256 "1f3138b0c956387de1b7b1af1a99b783ba1ebbb5cf453bcfe431aebcc8193412"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sapcc/limesctl/releases/download/v3.2.0/limesctl-3.2.0-linux-arm64.tar.gz"
      sha256 "fc160d47307525802098f11851ea9751b7f7b03f2823ddec5d91faca7a449f5f"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sapcc/limesctl/releases/download/v3.2.0/limesctl-3.2.0-linux-amd64.tar.gz"
      sha256 "610b73e81d8c309e9985ce136d13c8139bad3610685e561d54d67a0e2b11705b"

      def install
        bin.install "limesctl"
        bash_completion.install "completions/limesctl.bash" => "limesctl"
        zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
        fish_completion.install "completions/limesctl.fish"
      end
    end
  end

  test do
    system "#{bin}/limesctl --version"
  end
end
