run:
  deadline: 2m # 1m by default
  # Invoke with -mod=readonly. This ensures that the go command is disallowed
  # from the implicit automatic updating of go.mod. Instead, it fails when any
  # changes to go.mod are needed.
  # This setting is most useful to check that go.mod does not need updates,
  # such as in a continuous integration and testing system.
  modules-download-mode: readonly

linters:
  # Do not use 'enable-all', it is deprecated.
  # We use 'disable-all' and enable linters explicitly so that a newer version
  # will not introduce new linters unexpectedly.
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  dupl:
    # Tokens count to trigger issue, 150 by default.
    threshold: 100

  errcheck:
    # Report about assignment of errors to blank identifier:
    #   `num, _ := strconv.Atoi(numStr)`;
    check-blank: true

    # Report about not checking of errors in type assertions:
    #   `a := b.(MyStruct)`;
    check-type-assertions: true

    # Path to a file containing a list of functions to exclude from checking.
    # See https://github.com/kisielk/errcheck#excluding-functions for details.
    # exclude: ./.errcheck-excludes

  funlen:
      lines: 100
      statements: 50

  gci:
    # Put imports beginning with prefix after 3rd-party packages. It's a
    # comma-separated list of prefixes.
    local-prefixes: github.com/sapcc/limesctl

  goimports:
    local-prefixes: github.com/sapcc/limesctl

  lll:
    line-length: 140

  maligned:
    # Print structs with more effective memory layout or not, false by default.
    suggest-new: true

  whitespace:
    # Enforce newlines (or comments) after multi-line function signature.
    multi-func: true
  gocritic:
    disabled-checks:
      - commentFormatting
