before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sapcc/go-api-declarations/bininfo.binName=limesctl
      - -X github.com/sapcc/go-api-declarations/bininfo.version={{ .Version }}
      - -X github.com/sapcc/go-api-declarations/bininfo.commit={{ .FullCommit  }}
      # Use CommitDate instead of Date for reproducibility.
      - -X github.com/sapcc/go-api-declarations/bininfo.buildDate={{ .CommitDate }}
    # Set the modified timestamp on the output binary to ensure that builds are reproducible.
    mod_timestamp: "{{ .CommitTimestamp }}"

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: '{{ .ProjectName }}-{{ replace .Version "v" "" }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

brews:
  - tap:
      owner: sapcc
      name: limesctl
    folder: HomebrewFormula
    homepage: https://github.com/sapcc/limesctl
    description: Command-line interface for Limes
    license: Apache-2.0
    install: |
      bin.install "limesctl"
    test: |
      system "#{bin}/limesctl --version"
    commit_msg_template: "Homebrew: update formula to {{ .Tag }}"
