# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

version: 2
before:
  hooks:
    - rm -rf completions
    - mkdir completions
    - sh -c "for sh in bash zsh fish; do go run main.go completion "$sh" >"completions/limesctl.$sh"; done"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sapcc/go-api-declarations/bininfo.binName=limesctl
      - -X github.com/sapcc/go-api-declarations/bininfo.version={{ .Version }}
      - -X github.com/sapcc/go-api-declarations/bininfo.commit={{ .FullCommit  }}
      # Use CommitDate instead of Date for reproducibility.
      - -X github.com/sapcc/go-api-declarations/bininfo.buildDate={{ .CommitDate }}
    # Set the modified timestamp on the output binary to ensure that builds are reproducible.
    mod_timestamp: "{{ .CommitTimestamp }}"

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: '{{ .ProjectName }}-{{ replace .Version "v" "" }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - completions/*

brews:
  - repository:
      owner: sapcc
      name: limesctl
    directory: HomebrewFormula
    homepage: https://github.com/sapcc/limesctl
    description: Command-line interface for Limes
    license: Apache-2.0
    install: |-
      bin.install "limesctl"
      bash_completion.install "completions/limesctl.bash" => "limesctl"
      fish_completion.install "completions/limesctl.fish"
      zsh_completion.install "completions/limesctl.zsh" => "_limesctl"
    test: |
      system "#{bin}/limesctl --version"
    commit_msg_template: "Homebrew: update formula to {{ .Tag }}"
