name: goreleaser

# Run GoReleaser only on new tag.
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # By default, only a single commit is fetched for the ref/SHA that
          # triggered the workflow. We need `fetch-depth: 0` to fetch all
          # history for all branches and tags.
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: true
          go-version: "1.19"

      - name: Generate release info
        run: make build/release-info

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist --release-notes=./build/release-info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
